services:
  - type: web
    name: constitutio-api
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./startup.sh
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
